name: CI Pipeline

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Allow the workflow to push changes to the repository
  id-token: read    # Allow the workflow to request an OIDC token
  pull-requests: write  # Allow the workflow to create and update pull requests

jobs:
  checkov:
    name: Run Checkov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: checkov -d . --skip-check CKV_TF_1,CKV_TF_2

  tf-docs:
    name: Generate Terraform Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Install terraform-docs
        run: go install github.com/terraform-docs/terraform-docs@v0.16.0

      - name: Add Go bin to PATH
        run: echo "${{ github.workspace }}/go/bin" >> $GITHUB_PATH

      - name: Generate Terraform Documentation
        run: terraform-docs markdown table . > README.md

      - name: Commit Documentation
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Terraform documentation [skip ci]"

      - name: Pull Remote Changes
        run: git pull --rebase origin "${{ github.event.pull_request.head.ref }}"

      - name: Push Documentation
        run: git push origin "HEAD:${{ github.event.pull_request.head.ref }}"
