name: PR Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  checkov:
    name: Run Checkov
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov
        run: checkov -d .

  tf-docs:
    name: Generate Terraform Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Install terraform-docs
        run: |
          GO111MODULE=on go get github.com/terraform-docs/terraform-docs@v0.16.0

      - name: Generate Terraform Documentation
        run: terraform-docs markdown table . > README.md

      - name: Commit Documentation
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Terraform documentation [skip ci]"
          git push
