name: Terraform Docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  generate-docs:
    name: Generate Terraform Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Install terraform-docs
        uses: terraform-docs/gh-actions@v0.16.0

      - name: Generate docs
        run: terraform-docs markdown . > README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update Terraform docs"
          file_pattern: README.md
          branch: ${{ github.head_ref }}
